name: visual-sim-onnx
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24,<2.0        # 🧷 Pinned to avoid NumPy 2.x ABI incompatibilities
  - pytorch=1.13.1
  - torchvision=0.14.1
  - onnx=1.13.1
  - onnxruntime=1.18
  - opencv=4.6.0            # ✅ Compatible OpenCV version (avoid newer 4.9+ w/ NumPy 2)
  - pip:
      - torchsummary
